name: sponsorkit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  update-sponsors:
    name: Update sponsors
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Install dependencies
        run: bun install --production

      - name: Update sponsors
        run: bun run update
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}

      - name: If changed, commit and push
        run: |
          git config user.name 'ryoppippi'
          git config user.email '1560508+ryoppippi@users.noreply.github.com'
          git add . && git commit -m 'chore: update sponsors' || echo 'No changes to commit'
          git push origin main
