name: sponsorkit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Once a day

permissions:
  contents: write

jobs:
  update-sponsors:
    name: Update sponsors
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Install dependencies
        run: bun install --production

      - name: Update sponsors
        run: bun sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}

      - name: Commit
        run: |
          if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name 'ryoppippi'
          git config user.email '1560508+ryoppippi@users.noreply.github.com'
          git commit -am 'chore: update sponsors'
          git push
